apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: promescheduler-image
  newName: aimmopostregistry.azurecr.io/promescheduler
  newTag: ef0edbf0c0ce92a91fa620371d7f6bd90b7b1afb
- name: aimmopostregistry.azurecr.io/promescheduler
  newTag: latest

