apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: aimmopostregistry.azurecr.io/promescheduler
  newTag: 7d7c390af83a09d95cf4e3e89732da73df891fa3
- name: promescheduler-image
  newName: aimmopostregistry.azurecr.io/promescheduler
  newTag: v1
