apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: promescheduler-image
  newName: aimmopostregistry.azurecr.io/promescheduler
  newTag: v1
- name: aimmopostregistry.azurecr.io/promescheduler
  newTag: latest
