apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: monitoring
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
      - image: aimmopostregistry.azurecr.io/promescheduler:latest
        name: scheduler
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: scheduler
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: scheduler